service: talks
runtime: go111

env_variables:
  GOLANGORG_CHECK_COUNTRY: true

handlers:
- url: /favicon.ico
  static_files: static/favicon.ico
  upload: static/favicon.ico
  secure: always
- url: /static
  static_dir: static
  secure: always
- url: /.*
  script: auto
  secure: always

nobuild_files: content/
